### ISSUE TITLE
installation and usage?

### ISSUE THREAD

**Issue by yeungegs** [mitchellolsthoorn/starcraft-replay-highlighter#1]
This seems really interesting! I'm wondering if you have clear steps for installation and usage outlined elsewhere? Otherwise could they be added to README? 

Also, do you have [guidelines for contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)?

**Comment by mitchellolsthoorn** [comment]
Thank you for your interest. I will add the installation and usage instructions to the Readme and also add a contributing guideline. At the moment this program runs an analysis on csv data extracted from replay files. Currently the program can:

- roughly estimate if the player is a bot or a human
- calculate apm graphs and info
- calculate attack graphs and info
- calculate location graphs and info
- determine highlight from the above data

There is also a pull request that can create intermediate location map snapshots

**Comment by mitchellolsthoorn** [comment]
I added some basic instructions. The conversion part to csv, using another library is still a bit tedious right now. We plan on making a complete python version which is much simpler to use, Possible using [another replay file parser](https://github.com/GraylinKim/sc2reader) which we can integrate directly, without doing the conversion to csv.

If you have any question/problem with the installation, conversion or usage let me know, maybe I can help you. Also if you want some sample files to see what the script can produce than I can provide those.
